version: "3"

services:
  server:
    container_name: server-container
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        SERV_URL: ${SERV_URL}
        SERV_ENABLE_SSL: ${SERV_ENABLE_SSL}
        JWT_SECRET: ${JWT_SECRET}
        JWT_VALIDITY_DELTA: ${JWT_VALIDITY_DELTA}
        SERV_ENCRYPT_KEY: ${SERV_ENCRYPT_KEY}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
    depends_on:
      - database
    ports:
      - 8080:5000
    image: server-image
    extra_hosts:
      - "localhost:host-gateway"

  worker:
    container_name: worker-container
    build:
      context: ./worker
      dockerfile: Dockerfile
      args:
        WORKER_PING_ONLY: "false"
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
    depends_on:
      - database
    image: worker-image
    extra_hosts:
      - "localhost:host-gateway"

  web:
    container_name: web-container
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        SERV_ENABLE_SSL: ${SERV_ENABLE_SSL}
        SERV_URL: ${SERV_URL}
    depends_on:
      - server
    ports:
      - 8081:3000
    image: web-image
    extra_hosts:
      - "localhost:host-gateway"

  database:
    container_name: database-container
    ports:
      - 5432:5432
    image: postgres:11.8
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres-container-data:/var/lib/postgresql/data

  reverse_proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./server/certificates/fullchain.pem:/etc/nginx/fullchain.pem
      - ./server/certificates/privkey.pem:/etc/nginx/privkey.pem
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - web
      - server