name: Build Santa's Hood Worker Container

on:
  push:
    branches:
      - server
  pull_request:
    branches:
      - server

jobs:

  BuildWorker:
    runs-on: ubuntu-latest
    container: docker
    env:
      WORKER_PING_ONLY: true
    steps:
      - uses: actions/checkout@v2
      - name: Create worker container
        run: docker build -t worker-image worker/
      - name: Start worker container
        run: [[ "$(docker run --rm -e WORKER_PING_ONLY=true --name worker-container worker-image)" == "$(echo -e "-> Executing directory is [/app]\npong")" ]]

  BuildCompose:
    runs-on: ubuntu-latest
    env:
      WORKER_PING_ONLY: true
    steps:
      - uses: actions/checkout@v2
      - name: Start compose stack
        run:  docker-compose up -d worker
